# Generated by Django 5.2.8 on 2025-11-30 11:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MountainRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва маршруту')),
                ('description', models.TextField(verbose_name='Опис')),
                ('difficulty', models.CharField(choices=[('easy', 'Легка'), ('medium', 'Середня'), ('hard', 'Важка')], max_length=10, verbose_name='Складність')),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Висота (м)')),
                ('duration_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='Тривалість (годин)')),
                ('distance_km', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Відстань (км)')),
                ('image', models.ImageField(upload_to='routes/', verbose_name='Основне фото')),
                ('map_coordinates', models.CharField(max_length=100, verbose_name='Координати (lat,lng)')),
                ('gpx_file', models.FileField(blank=True, null=True, upload_to='gpx/', verbose_name='GPX файл маршруту')),
                ('region', models.CharField(max_length=100, verbose_name='Регіон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'Гірський маршрут',
                'verbose_name_plural': 'Гірські маршрути',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Біографія')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_routes', models.ManyToManyField(blank=True, related_name='completed_by', to='mountains_roads.mountainroute', verbose_name='Пройдені маршрути')),
                ('favorite_routes', models.ManyToManyField(blank=True, related_name='favorited_by', to='mountains_roads.mountainroute', verbose_name='Улюблені маршрути')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
            },
        ),
        migrations.CreateModel(
            name='RouteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оцінка')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок відгуку')),
                ('text', models.TextField(verbose_name='Текст відгуку')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Кількість корисних')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mountains_roads.mountainroute', verbose_name='Маршрут')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
                'unique_together': {('route', 'user')},
            },
        ),
    ]
